baseURL: https://hoppydicetactics.ch
title: Hoppy Dice Tactics
module:
  imports:
    - path: github.com/526avijitgupta/gokarna
    - path: github.com/martignoni/hugo-cloak-email
enableEmoji: true
enableRobotsTXT: true

defaultContentLanguage: de
defaultContentLanguageInSubdir: true
languages:
  de:
    contentDir: content/de
    languageCode: de
    languageDirection: ltr
    languageName: DE
    params:
      customFooterHTML: |
        <span><a href="/de/privacy-policy/">Datenschutzerklärung</a></span>
      dateFormat: "2. January 2006"
    weight: 1
  en:
    contentDir: content/en
    languageCode: en
    languageDirection: ltr
    languageName: EN
    params:
      customFooterHTML: |
        <span><a href="/en/privacy-policy/">Privacy Policy</a></span>
      dateFormat: "2 January, 2006"
    weight: 2

params:
  description: Warhammer 40,000 Community in Bern
  accentColor: "#E08A33"
  avatarURL: /images/logo.webp
  AvatarAltText: Hoppy Dice Tactics
  avatarSize: size-l
  fontSize: 16px
  socialIcons:
    - name: discord
      url: https://discord.gg/Z8qSE5QNu6
  metaKeywords:
    - Hoppy Dice Tactics
    - Warhammer 40000
    - Warhammer 40k
    - Bern
    - Breitenrain
  customHeadHTML: |
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="stylesheet" type="text/css" href="/css/hoppy.css">

markup:
  tableOfContents:
    startLevel: 1
    endLevel: 4
