baseURL: https://hoppydicetactics.ch
title: Hoppy Dice Tactics
languageCode: de
defaultContentLanguage: de
module:
  imports:
    path: github.com/526avijitgupta/gokarna
enableEmoji: true
enableRobotsTXT: true

params:
  description: Warhammer 40,000 Team in Bern
  accentColor: "#E08A33"
  avatarURL: images/logo.webp
  AvatarAltText: Hoppy Dice Tactics
  avatarSize: size-l
  socialIcons:
    - name: discord
      url: https://discord.gg/9tB4zShDbn
    - name: email
      url: /contact/
  metaKeywords:
    - bern
    - warhammer
    - 40000
    - 40k
    - kill team
    - competitive
  customHeadHTML: |
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/site.webmanifest">
        <link rel="stylesheet" type="text/css" href="/css/hoppy.css">
  customFooterHTML: |
    <span><a href="/privacy-policy/">Datenschutzerklärung</a></span>

menu:
  main:
    - name: Kontakt
      pre: <span data-feather='mail'></span>
      url: /contact/
      weight: 1
    - name: Erste Schritte
      pre: <span data-feather='play'></span>
      url: /getting-started/
      weight: 2
    - name: Terrain Layouts
      pre: <span data-feather='map'></span>
      url: /terrain-layouts/
      weight: 3
    - identifier: github
      pre: <span data-feather='github'></span>
      url: https://github.com/hoppydicetactics/website
      weight: 4

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 2
