main:
  - name: Über uns
    pre: <span data-feather='users'></span>
    url: /de/about/
    weight: 1
  - name: Starten mit Warhammer 40.000
    pre: <span data-feather='play'></span>
    url: /de/getting-started/
    weight: 2
  - name: Terrain Layouts
    pre: <span data-feather='map'></span>
    url: /de/terrain-layouts/
    weight: 3
  - identifier: contact
    pre: <img class='svg-inject' src='/svg/icons/email.svg' />
    url: /de/contact/
    weight: 11
  - identifier: discord
    pre: <img class='svg-inject' src='/svg/icons/discord.svg' />
    url: https://discord.gg/Z8qSE5QNu6
    weight: 12
    params:
      newPage: true
  - identifier: github
    pre: <img class='svg-inject' src='/svg/icons/github.svg' />
    url: https://github.com/hoppydicetactics/website
    weight: 13
    params:
      newPage: true
