params:
  customHeadHTML: |
    <script async src="https://analytics.umami.is/script.js" data-website-id="6275a9ce-bf8b-4475-81f5-3ca835d022ae" data-do-not-track="true"></script>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/site.webmanifest">
        <link rel="stylesheet" type="text/css" href="/css/hoppy.css">
